apiVersion: v1
entries:
  kubefed:
  - apiVersion: v2
    created: "2021-06-28T20:33:21.723244824+01:00"
    dependencies:
    - condition: controllermanager.enabled
      name: controllermanager
      repository: https://localhost/
      version: 0.8.1
    description: KubeFed helm chart
    digest: a1a82e660978796f2c93a967ab058f74ba9b20861305eb43f5a9c133791fe3e2
    kubeVersion: '>= 1.16.0-0'
    name: kubefed
    urls:
    - https://github.com/kubernetes-sigs/kubefed/releases/download/v0.8.1/kubefed-0.8.1.tgz
    version: 0.8.1
generated: "2021-07-16T20:33:21.721469952+01:00"
